accounts:
  - id: 1001
    status: active
    auction:
      price-granularity: low
      debug-allow: false
      "banner-cache-ttl": 1
      "video-cache-ttl": 1
    settings:
      geo-lookup: true
    privacy:
      ccpa:
        enabled: true
      gdpr:
        enabled: true
    cookie-sync:
      default-limit: 8
      max-limit: 15
      coop-sync:
        default: true
